/turtlesim:
  ros__parameters:
    background_b: 10
    background_g: 156
    background_r: 44
    holonomic: false
    qos_overrides:
      /parameter_events:
        publisher:
          depth: 1000
          durability: volatile
          history: keep_last
          reliability: reliable
    start_type_description_service: true
    use_sim_time: false

